# Lab 1: Basic NumPy Operations

**Date:** 2026-02-02  
**Student Name:** [Your Name]  
**Student ID:** [Your ID]

**Topics Covered:**
- NumPy Array Creation and Operations
- 2-D Array Indexing and Slicing
- Array Stacking and Splitting
- Matrix Operations and Multiplication
- Array Reshaping and Broadcasting
- Solving Systems of Linear Equations

---

## Setup

Import the necessary libraries for NumPy operations.

In [6]:
# Import NumPy library
import numpy as np

# Set print options for better readability
np.set_printoptions(precision=4, suppress=True)

## Part A: NumPy Array Operations

### Question 2: Create an Array with Specific Range

Create an array that starts from integer 1, ends at 20, incremented by 3.

In [7]:
# Create array starting from 1, ending at 20, incremented by 3
arr_range = np.arange(1, 21, 3)
print("Array from 1 to 20 with step 3:")
print(arr_range)
print(f"Shape: {arr_range.shape}")


Array from 1 to 20 with step 3:
[ 1  4  7 10 13 16 19]
Shape: (7,)


### Question 3: Create Random Array

Create a new array of shape 3 with random numbers between 0 and 1.

In [11]:
# Create array of shape 3 with random numbers between 0 and 1
arr_random = np.random.rand(3)
print("Random array of shape 3:")
print(arr_random)
print(f"Shape: {arr_random.shape}")


Random array of shape 3:
[0.2975 0.4431 0.0545]
Shape: (3,)


### Question 4: 2D Array Slicing

Create a 2D array [[10,20,45], [30,12,16], [42,17,56]] and perform slicing operations.

# Create 2D array
arr_2d = np.array([[10, 20, 45], [30, 12, 16], [42, 17, 56]])
print("Original 2D array:")
print(arr_2d)
print(f"Shape: {arr_2d.shape}")

In [12]:
arr_2d = np.array([[10, 20, 45], [30, 12, 16], [42, 17, 56]])
# Slice the first two rows
first_two_rows = arr_2d[:2, :]
print("First two rows:")
print(first_two_rows)
print()

# Slice the last two rows
last_two_rows = arr_2d[-2:, :]
print("Last two rows:")
print(last_two_rows)


First two rows:
[[10 20 45]
 [30 12 16]]

Last two rows:
[[30 12 16]
 [42 17 56]]


### Question 5: Array Stacking and Splitting

Create two 2x2 arrays and demonstrate vertical stacking, horizontal stacking, and splitting.

# Create two 2x2 arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print()

In [13]:
# Vertical stacking (vstack)
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

vertical_stack = np.vstack((array1, array2))
print("Vertical Stack (vstack):")
print(vertical_stack)
print(f"Shape: {vertical_stack.shape}")
print()

# Horizontal stacking (hstack)
horizontal_stack = np.hstack((array1, array2))
print("Horizontal Stack (hstack):")
print(horizontal_stack)
print(f"Shape: {horizontal_stack.shape}")
print()

# Split horizontally stacked array
split_arrays = np.hsplit(horizontal_stack, 2)
print("Split horizontal stack into 2 arrays:")
print("First split:")
print(split_arrays[0])
print("Second split:")
print(split_arrays[1])


Vertical Stack (vstack):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Shape: (4, 2)

Horizontal Stack (hstack):
[[1 2 5 6]
 [3 4 7 8]]
Shape: (2, 4)

Split horizontal stack into 2 arrays:
First split:
[[1 2]
 [3 4]]
Second split:
[[5 6]
 [7 8]]


### Question 6: Matrix Multiplication

Create matrices X = [[5, 7, 2], [4, 5, 6], [7, 4, 2]] and Y = [[4, 2], [6, 2], [4, 2]].
Determine if multiplication is possible and demonstrate when it's not.

In [14]:
# Create matrices
X = np.array([[5, 7, 2], [4, 5, 6], [7, 4, 2]])
Y = np.array([[4, 2], [6, 2], [4, 2]])

print("Matrix X:")
print(X)
print(f"Shape: {X.shape}")
print()

print("Matrix Y:")
print(Y)
print(f"Shape: {Y.shape}")
print()

# Check if multiplication is possible
# For matrix multiplication X @ Y, X's columns must equal Y's rows
print(f"X has {X.shape[1]} columns, Y has {Y.shape[0]} rows")
print(f"Can we multiply X @ Y? {X.shape[1] == Y.shape[0]}")
print()

# Perform multiplication X @ Y (possible)
result_XY = np.matmul(X, Y)
print("Result of X @ Y:")
print(result_XY)
print(f"Shape: {result_XY.shape}")


Matrix X:
[[5 7 2]
 [4 5 6]
 [7 4 2]]
Shape: (3, 3)

Matrix Y:
[[4 2]
 [6 2]
 [4 2]]
Shape: (3, 2)

X has 3 columns, Y has 3 rows
Can we multiply X @ Y? True

Result of X @ Y:
[[70 28]
 [70 30]
 [60 26]]
Shape: (3, 2)


### Question 7: Array Creation, Shape, and Reshaping

Create two arrays x and y, find their shapes and dimensions, then reshape them and analyze the results.

In [ ]:
# Create vectors x and y
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

print("Vector x:", x)
print("Vector y:", y)
print()

# Find shape and number of dimensions of vector x
print("=== Vector x Properties ===")
print(f"Shape of x: {x.shape}")
print(f"Number of dimensions of x: {x.ndim}")
print()

# Reshape x to a matrix of size (3, 1)
x_reshaped = x.reshape(3, 1)
print("=== Reshaped x to (3, 1) ===")
print("x_reshaped:")
print(x_reshaped)
print(f"Shape of x_reshaped: {x_reshaped.shape}")
print(f"Number of dimensions of x_reshaped: {x_reshaped.ndim}")
print()

# Reshape y to a matrix of size (3, 1)
y_reshaped = y.reshape(3, 1)
print("=== Reshaped y to (3, 1) ===")
print("y_reshaped:")
print(y_reshaped)
print(f"Shape of y_reshaped: {y_reshaped.shape}")
print(f"Number of dimensions of y_reshaped: {y_reshaped.ndim}")

### Question 8: Broadcasting

Broadcasting is NumPy's ability to perform operations on arrays of different shapes. When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions and works its way forward. Two dimensions are compatible when:
1. They are equal, or
2. One of them is 1

Demonstrate subtraction and multiplication with broadcasting using a 3x3 matrix.

In [ ]:
# Create a 3x3 matrix
matrix_3x3 = np.array([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

print("Original 3x3 matrix:")
print(matrix_3x3)
print()

# Broadcasting with a scalar (0-dimensional)
scalar = 5
print(f"Subtract scalar ({scalar}) from matrix:")
result_subtract_scalar = matrix_3x3 - scalar
print(result_subtract_scalar)
print()

print(f"Multiply matrix by scalar ({scalar}):")
result_multiply_scalar = matrix_3x3 * scalar
print(result_multiply_scalar)
print()

# Broadcasting with a 1D array (row vector)
row_vector = np.array([1, 2, 3])
print(f"Subtract row vector {row_vector} from matrix:")
result_subtract_row = matrix_3x3 - row_vector
print(result_subtract_row)
print()

print(f"Multiply matrix by row vector {row_vector}:")
result_multiply_row = matrix_3x3 * row_vector
print(result_multiply_row)
print()

# Broadcasting with a column vector
col_vector = np.array([[10], [20], [30]])
print("Subtract column vector from matrix:")
print(col_vector)
result_subtract_col = matrix_3x3 - col_vector
print(result_subtract_col)
print()

print("Multiply matrix by column vector:")
result_multiply_col = matrix_3x3 * col_vector
print(result_multiply_col)

---

## Part B: Solving Systems of Linear Equations

### Question 1: Solve Linear Systems

We will solve two systems of linear equations using NumPy's linear algebra package.

#### System 1:
$$
\begin{align}
2x_1 + 3x_2 - 4x_3 &= 6 \\
x_1 - 4x_2 &= 8
\end{align}
$$

This system has 2 equations with 3 unknowns (underdetermined system).

In [ ]:
# System 1: 2x1 + 3x2 - 4x3 = 6, x1 - 4x2 = 8
# Coefficient matrix A and constants vector b
A1 = np.array([[2, 3, -4],
               [1, -4, 0]])
b1 = np.array([6, 8])

print("System 1:")
print("Coefficient matrix A:")
print(A1)
print(f"Shape: {A1.shape}")
print()
print("Constants vector b:")
print(b1)
print()

# Check the rank of the system
rank_A1 = np.linalg.matrix_rank(A1)
rank_Ab1 = np.linalg.matrix_rank(np.column_stack((A1, b1)))

print(f"Rank of A: {rank_A1}")
print(f"Rank of [A|b]: {rank_Ab1}")
print(f"Number of unknowns: {A1.shape[1]}")
print()

if rank_A1 == rank_Ab1:
    if rank_A1 < A1.shape[1]:
        print("System is UNDERDETERMINED: Infinitely many solutions exist.")
        print("Using least squares solution (one particular solution):")
        solution1, residuals, rank, s = np.linalg.lstsq(A1, b1, rcond=None)
        print(f"One solution: x1 = {solution1[0]:.4f}, x2 = {solution1[1]:.4f}, x3 = {solution1[2]:.4f}")
    else:
        print("System has a UNIQUE solution.")
        solution1 = np.linalg.solve(A1, b1)
        print(f"Solution: x1 = {solution1[0]:.4f}, x2 = {solution1[1]:.4f}, x3 = {solution1[2]:.4f}")
else:
    print("System is INCONSISTENT: No solution exists.")

#### System 2:
$$
\begin{align}
3y_1 - 4y_2 + 5y_3 &= 10 \\
-y_1 + 2y_2 - 4y_3 &= 8
\end{align}
$$

This system also has 2 equations with 3 unknowns (underdetermined system).

In [ ]:
# System 2: 3y1 - 4y2 + 5y3 = 10, -y1 + 2y2 - 4y3 = 8
# Coefficient matrix A and constants vector b
A2 = np.array([[3, -4, 5],
               [-1, 2, -4]])
b2 = np.array([10, 8])

print("System 2:")
print("Coefficient matrix A:")
print(A2)
print(f"Shape: {A2.shape}")
print()
print("Constants vector b:")
print(b2)
print()

# Check the rank of the system
rank_A2 = np.linalg.matrix_rank(A2)
rank_Ab2 = np.linalg.matrix_rank(np.column_stack((A2, b2)))

print(f"Rank of A: {rank_A2}")
print(f"Rank of [A|b]: {rank_Ab2}")
print(f"Number of unknowns: {A2.shape[1]}")
print()

if rank_A2 == rank_Ab2:
    if rank_A2 < A2.shape[1]:
        print("System is UNDERDETERMINED: Infinitely many solutions exist.")
        print("Using least squares solution (one particular solution):")
        solution2, residuals, rank, s = np.linalg.lstsq(A2, b2, rcond=None)
        print(f"One solution: y1 = {solution2[0]:.4f}, y2 = {solution2[1]:.4f}, y3 = {solution2[2]:.4f}")
    else:
        print("System has a UNIQUE solution.")
        solution2 = np.linalg.solve(A2, b2)
        print(f"Solution: y1 = {solution2[0]:.4f}, y2 = {solution2[1]:.4f}, y3 = {solution2[2]:.4f}")
else:
    print("System is INCONSISTENT: No solution exists.")

---

## Summary and Key Takeaways

### Overview of Lab Operations

This lab demonstrated fundamental NumPy operations essential for numerical computing and data analysis:

1. **Array Creation**: We created arrays using `np.arange()` for sequential values and `np.random.rand()` for random values, which are essential for generating test data and performing simulations.

2. **2D Array Slicing**: We practiced slicing operations on 2D arrays to extract specific rows, demonstrating how to efficiently access and manipulate multi-dimensional data structures.

3. **Array Stacking and Splitting**: We explored `vstack()` and `hstack()` for combining arrays vertically and horizontally, and `hsplit()` for splitting arrays, which are crucial for data organization and transformation.

4. **Matrix Multiplication**: We verified the conditions for matrix multiplication (inner dimensions must match) and demonstrated both valid and invalid multiplication scenarios using `np.matmul()`.

5. **Array Shape and Reshaping**: We examined array properties (`shape`, `ndim`) and used `reshape()` to transform 1D arrays into column vectors, which is fundamental for proper matrix operations.

6. **Broadcasting**: We demonstrated NumPy's broadcasting mechanism, which allows operations between arrays of different shapes by automatically expanding dimensions, making vectorized operations more flexible and efficient.

7. **Linear Systems**: We solved underdetermined systems of linear equations using `np.linalg.lstsq()` and analyzed the rank of coefficient matrices to determine the nature of solutions (unique, infinite, or no solution).

### Key Concepts Learned

- NumPy arrays provide efficient storage and operations for numerical data
- Matrix operations require careful attention to dimensions and shapes
- Broadcasting enables elegant vectorized operations without explicit loops
- Linear algebra functions in NumPy can solve complex systems of equations
- Understanding array ranks helps determine the solvability of linear systems

### Note on Publishing

As per Part B, Question 2: This notebook should be published as an HTML file on GitHub Pages two weeks after the due date.